// GENERIC
export const RESET_STATE = 'RESET_STATE';

// ALERTS
export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// USERS
export const SET_TOKEN = 'SET_TOKEN';

//Stocks
export const ADD_MISC_STOCK = 'ADD_MISC_STOCK';
export const ADD_MAPPED_PLACEHOLDER = 'ADD_MAPPED_PLACEHOLDER';
export const ADD_MAPPED_STOCK = 'ADD_MAPPEDSTOCK';
export const REMOVE_MAPPED_STOCK = 'REMOVE_MAPPED_STOCK';
